import {supabase} from './supabase-client.js';
const $=s=>document.querySelector(s),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,profile=null,companies=[],current=null,requests=[],previews=[];
const sections={overview:['Overview','Your Steady Hands workspace'],website:['My Website','Website and domain details'],emails:['Business Emails','Email accounts and setup'],admin:['Admin Site','Your private management dashboard'],requests:['Requests','Website changes and support'],billing:['Billing & Plans','Subscriptions and payments'],referrals:['Referrals & Rewards','Referral information'],support:['Help & Support','Contact Steady Hands'],settings:['Settings','Manage your profile']};
function pageHeader(t,d){return '<div class="pagehead"><h1>'+safe(t)+'</h1><p>'+safe(d)+'</p></div>'}
function empty(t,message){return '<div class="panel empty-workspace"><h2>'+safe(t)+'</h2><p>'+safe(message)+'</p></div>'}
const links=(arr)=>'<div class="mini-list">'+arr.map(x=>'<a target="_blank" rel="noopener noreferrer" href="'+safe(x.url)+'">'+safe(x.text)+'</a>').join('')+'</div>';
function isCompanyAvailable(){return Boolean(current?.status==='verified')}
const button=(label,page)=>'<button class="primary" data-page="'+page+'">'+label+'</button>';
const panel=(heading,body)=>'<section class="panel"><h3>'+heading+'</h3>'+body+'</section>';
const requestTypes={website:'New Website',preview:'Request a Preview',change:'Website Changes',email:'Business Email',admin:'Admin Access',billing:'Billing Question',support:'Support',other:'Other'};
function previewCards(){return previews.length?previews.map(p=>panel(safe(p.site_title),'<p><b>Site key:</b> '+safe(p.site_key)+'</p><div class="actions"><a class="primary" target="_blank" rel="noopener noreferrer" href="'+safe(p.preview_url)+'">Open Preview</a><button class="secondary" data-share="'+safe(p.preview_url)+'">Share Preview</button></div>')).join(''):panel('Your previews','<p>No preview is assigned to your verified company yet. Request one below.</p>'+button('Request a Preview','requests'))}
function pageContent(p){
 const [title,subtitle]=sections[p],business=safe(current?.company_name||user.user_metadata?.portal_company_name||'Your Business');
 if(p==='overview')return '<section class="hero"><span class="eyebrow">WE RUN THE SITE. YOU RUN THE SHOW.</span><h1>Welcome, '+safe(profile.full_name.split(' ')[0])+'!</h1><p>Get your business online, track requests, and manage your services.</p><div class="actions">'+button('Get Your Website','website')+' '+button('Request a Preview','requests')+'</div></section><div class="section-title"><h2>Getting started</h2></div>'+panel('Your next steps','<p>Account created ✓ &nbsp; · &nbsp; Request a website or preview &nbsp; · &nbsp; Choose hosting &nbsp; · &nbsp; Launch</p>')+previewCards()+panel('Recent requests',requests.length?requests.slice(0,3).map(r=>'<p>'+safe(r.title)+' — '+safe(r.status.replaceAll('_',' '))+'</p>').join(''):'<p>No requests submitted yet.</p>');
 if(p==='website')return pageHeader(title,'Create your website or manage an assigned preview.')+panel('Start your website','<p>Tell us about your business and the website you need.</p><div class="actions"><a class="primary" href="https://steadyhandsop.com/make-site.html" target="_blank" rel="noopener noreferrer">Create My Website</a>'+button('Request a Custom Website','requests')+'</div>')+panel('Your website previews',previewCards())+panel('Already have a site key?','<p>Enter your site key in a support request so we can verify and link your website. A site key alone does not grant access.</p>'+button('Request Site Linking','requests'));
 if(p==='requests')return pageHeader(title,'Submit and track website and service requests.')+panel('New request','<form id="request-form" class="profile-form"><label for="type">Request type *</label><select id="type" required>'+Object.entries(requestTypes).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select><label for="request-title">Subject *</label><input id="request-title" required maxlength="160" placeholder="What can we help you with?"><label for="request-details">Details *</label><textarea id="request-details" required rows="5" maxlength="5000" placeholder="Describe what you need. You can include an existing site key here."></textarea><button class="primary" type="submit">Submit Request</button><p id="request-message" role="status"></p></form>')+panel('Your request history',requests.length?requests.map(r=>'<div class="rowlist"><div><strong>'+safe(r.title)+'</strong><small>'+safe(requestTypes[r.request_type]||r.request_type)+' · '+new Date(r.created_at).toLocaleDateString()+'</small></div><span class="tag">'+safe(r.status.replaceAll('_',' '))+'</span></div>').join(''):'<p>You have not submitted a request yet.</p>');
 if(p==='billing')return pageHeader(title,'Choose hosting that fits your business.')+'<div class="twocol">'+[["Standard Hosting",20,"Hosting and essential maintenance."],["Backend Hosting",30,"Hosting with eligible backend management features."]].map(v=>panel(v[0],'<div class="price">$'+v[1]+'<span class="muted small"> / month</span></div><p>'+v[2]+'</p><button class="primary" data-select-plan="'+v[0]+'">Select Plan</button>')).join('')+'</div>'+panel('Website Development','<p>One-time development is $100, separate from monthly hosting.</p>')+panel('Payments and subscriptions','<p>No verified payment history is connected to this portal yet. Selecting a plan will start a request, not charge your card.</p>');
 if(p==='emails')return pageHeader(title,'Get professional email addresses for your business.')+panel('Business Email','<p>Additional business mailboxes cost $2/month or $24/year each. Email setup requires an eligible domain and provisioning by Steady Hands.</p>'+button('Request Business Email','requests'));
 if(p==='admin')return pageHeader(title,'Manage your website content with eligible backend hosting.')+panel('Backend Access','<p>Backend Hosting is $30/month and may include controls for your services, products, and reviews, depending on your site.</p>'+button('Request Admin Access','requests')+' '+button('View Hosting Plans','billing'));
 if(p==='referrals')return pageHeader(title,'Invite businesses to Steady Hands.')+panel('Your referrals','<p>Your submitted referral code: <strong>'+safe(user.user_metadata?.portal_referral_code||'None')+'</strong></p><p>Referral rewards and personal sharing links will appear once the referral program is connected. Entered codes are not yet validated.</p>');
 if(p==='support')return pageHeader(title,'We are here to help.')+panel('Contact Steady Hands','<p>Email <a href="mailto:kiara@steadyhandsop.com">kiara@steadyhandsop.com</a>, or submit a support request and track its status.</p>'+button('Submit Support Request','requests'));
 if(p==='settings')return pageHeader(title,'Update your account details.')+panel('Your profile','<form id="profile" class="profile-form"><label for="full-name">Display name *</label><input id="full-name" maxlength="120" required value="'+safe(profile.full_name)+'"><label for="company-name">Company name *</label><input id="company-name" maxlength="160" required value="'+safe(user.user_metadata?.portal_company_name||'')+'"><label>Email</label><div class="notice">'+safe(user.email)+'</div><button class="primary" type="submit">Save Changes</button><p id="profile-message" role="status"></p></form>');
 return pageHeader(title,subtitle);
}
function render(){const p=sections[location.hash.slice(1)]?location.hash.slice(1):'overview';$('#main').innerHTML=pageContent(p);$('#main').scrollTop=0;document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===p));if(p==='settings')$('#profile').addEventListener('submit',saveProfile);if(p==='requests'){$('#request-form').addEventListener('submit',submitRequest);const value=sessionStorage.getItem('portal_request_type');if(value&&requestTypes[value]){$('#type').value=value;sessionStorage.removeItem('portal_request_type')}}closeSidebar()}
async function saveProfile(e){e.preventDefault();const button=e.target.querySelector('button[type=submit]');button.disabled=true;const name=$('#full-name').value.trim(),company=$('#company-name').value.trim();if(!name||!company){$('#profile-message').textContent='Both fields are required.';button.disabled=false;return}const {error:metadataError}=await supabase.auth.updateUser({data:{portal_company_name:company}});if(metadataError){$('#profile-message').textContent=metadataError.message;button.disabled=false;return}user.user_metadata={...user.user_metadata,portal_company_name:company};const {error}=await supabase.from('portal_profiles').upsert({user_id:user.id,full_name:name,updated_at:new Date().toISOString()},{onConflict:'user_id'});$('#profile-message').textContent=error?error.message:'Saved successfully.';if(!error)profile.full_name=name;button.disabled=false}
async function submitRequest(e){e.preventDefault();const button=e.target.querySelector('button[type=submit]');button.disabled=true;const record={user_id:user.id,company_name:user.user_metadata?.portal_company_name||'',request_type:$('#type').value,title:$('#request-title').value.trim(),details:$('#request-details').value.trim()};const {error}=await supabase.from('portal_service_requests').insert(record);if(error){$('#request-message').textContent='Request could not be saved. The portal requests database setup may still be needed: '+error.message;button.disabled=false;return}await loadRecords();render()}
async function loadRecords(){const a=await supabase.from('portal_service_requests').select('id,request_type,title,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);requests=a.data||[];const b=await supabase.from('portal_previews').select('id,site_title,site_key,preview_url').limit(50);previews=b.data||[]}
function closeSidebar(){setSidebar(false)}
function setSidebar(on){const active=window.matchMedia('(max-width:760px)').matches&&on;$('#sidebar').classList.toggle('open',active);$('#sidebar-backdrop').classList.toggle('open',active);$('#menu').setAttribute('aria-expanded',String(active))}
$('#menu').onclick=()=>setSidebar(!$('#sidebar').classList.contains('open'));$('#sidebar-backdrop').onclick=closeSidebar;
$('#nav').addEventListener('click',e=>{const button=e.target.closest('[data-page]');if(button)location.hash=button.dataset.page});
$('#main').addEventListener('click',async e=>{const share=e.target.closest('[data-share]');if(share){const url=share.dataset.share;if(navigator.share){try{await navigator.share({title:'Website Preview',url})}catch{}}else if(navigator.clipboard){await navigator.clipboard.writeText(url);share.textContent='Link Copied'}return}const plan=e.target.closest('[data-select-plan]');if(plan){sessionStorage.setItem('portal_request_type','billing');location.hash='requests';return}const button=e.target.closest('[data-page]');if(button){if(button.textContent.includes('Preview'))sessionStorage.setItem('portal_request_type','preview');else if(button.textContent.includes('Website'))sessionStorage.setItem('portal_request_type','website');location.hash=button.dataset.page;render()}});
window.addEventListener('hashchange',render);window.addEventListener('resize',()=>{if(innerWidth>760)closeSidebar()});
let gesture;
document.addEventListener('touchstart',e=>{if(innerWidth>760||e.touches.length!==1||e.target.closest('input,textarea,select,[contenteditable]')){gesture=null;return}gesture={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});
document.addEventListener('touchend',e=>{if(!gesture||innerWidth>760)return;const dx=e.changedTouches[0].clientX-gesture.x,dy=e.changedTouches[0].clientY-gesture.y;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.6)setSidebar(dx>0);gesture=null},{passive:true});
$('#logout').onclick=async()=>{await supabase.auth.signOut();location.replace('login.html')};
async function boot(){const {data:{session},error}=await supabase.auth.getSession();if(error||!session){location.replace('login.html');return}user=session.user;$('#avatar').textContent=(user.email||'SH').slice(0,2).toUpperCase();
 const p=await supabase.from('portal_profiles').select('full_name,phone').eq('user_id',user.id).maybeSingle();
 if(p.error){$('#main').innerHTML=empty('Unable to load profile',p.error.message);return}profile=p.data||{full_name:'',phone:''}; if(!profile.full_name?.trim()||!String(user.user_metadata?.portal_company_name||'').trim()){location.replace('onboarding.html');return;}
 const m=await supabase.from('portal_memberships').select('company_id,role').eq('user_id',user.id);
 if(m.error){$('#main').innerHTML=empty('Unable to load memberships',m.error.message);return}
 if(m.data?.length){const ids=m.data.map(x=>x.company_id);const c=await supabase.from('portal_companies').select('id,company_name,status').in('id',ids);if(c.error){$('#main').innerHTML=empty('Unable to load companies',c.error.message);return}companies=c.data||[];current=companies[0]||null}
 await loadRecords();$('#company-label').textContent=current?.company_name||user.user_metadata?.portal_company_name||'My Workspace';$('#company-letter').textContent=(current?.company_name||user.user_metadata?.portal_company_name||'S').charAt(0).toUpperCase();render();
}
supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')location.replace('login.html')});boot();
